"""
Runs the Heuristic approach from "Cost-Aware Replicas Placement and Tasks Scheduling
In Geo-Distributed Infrastructure" (Si-Mohammed et al.) on a trace generated by
generate_traces.py, and reports the paper's key metrics:
  - avg flow time (Section 5.2, Fig. 2/4)
  - total volume of data transferred (Fig. 5, Table 3)
  - number of transfers / accepted replications vs opportunities (Table 3)

The heuristic itself (utility function + acceleration factor, threshold sigma - eq.
15-18 of the paper) is already implemented in this folder (copied from the full
repository, see README.md): heuristic_scheduler.SelectionnerMeilleurNoeud, invoked by
master_node_with_heterogeneous_nodes.UtilityBasedHeterogeneousApproach.checkUtilityProblem.
This script just plugs a generated trace into that engine - no reimplementation.

The paper does not model a storage constraint (nodes have unlimited capacity, see
generate_traces.py) or migration/preemption: those strategies (handled elsewhere in the
full repository) have been removed from this artifact - heuristic_scheduler.py and
master_node_with_heterogeneous_nodes.py only contain the paper's decision logic here
(adding a replica onto a genuinely free node).

100% self-contained artifact: every file needed is in this folder (no import or path
reaches outside paper-artifact/).

Usage:
    python3 run_heuristic.py traces/inst-20J-50N --sigma 0.05
    python3 run_heuristic.py traces/inst-20J-50N --sigma 0.10

`--sigma` matches the paper's sigma parameter (minimum improvement threshold, section
4.2) = master_node_with_heterogeneous_nodes/heuristic_scheduler's
acceleration_threshold - the SMALLER sigma is, the MORE easily the heuristic accepts a
replica (behavior close to "always accelerate"); the larger, the more selective it is
(less replication, cf. Fig. 6 of the paper).
"""
import argparse
import json
import os
import sys

ARTIFACT_ROOT = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, ARTIFACT_ROOT)  # everything is local to this folder - see README.md

import numpy as np
import simpy

from tracker import Tracker
from compute_node import ComputeNode
from master_node_with_heterogeneous_nodes import UtilityBasedHeterogeneousApproach
from engine import generateHeterogeneousInfrastructureEquilibre, jobs_injector


def load_base_config():
    with open(os.path.join(ARTIFACT_ROOT, "config.json")) as f:
        return json.load(f)


def run_instance(instance_dir: str, sigma: float, until: float = 200000):
    infra_csv = os.path.join(instance_dir, "infrastructure.csv")
    jobs_file = os.path.join(instance_dir, "jobs.json")
    with open(jobs_file) as f:
        nb_jobs = len(json.load(f))

    config = load_base_config()
    config["jobs_file_path"] = jobs_file
    config["total_nb_jobs"] = nb_jobs
    config["adaptive_acceleration_threshold"] = False
    config["with_acceleration"] = True
    config["acceleration_threshold"] = sigma
    config["rl-agent"] = False

    # generateHeterogeneousInfrastructureEquilibre prints every node to stdout - we
    # temporarily silence it to keep this script's output readable.
    _stdout = sys.stdout
    sys.stdout = open(os.devnull, "w")
    try:
        nodes_config = generateHeterogeneousInfrastructureEquilibre(config, path=infra_csv)
    finally:
        sys.stdout.close()
        sys.stdout = _stdout
    config["total_nb_compute_nodes"] = len(nodes_config)

    env = simpy.Environment()
    tracker = Tracker(env)
    master = UtilityBasedHeterogeneousApproach(env, [], tracker, config, overlap=config.get("overlap", False))
    compute_nodes = [
        ComputeNode(env, i, master, bandwidth=nodes_config[i]["bandwidth"],
                    compute_capacity=1 / nodes_config[i]["computation_nodes"],
                    energy_consumption=nodes_config[i]["energy_consumption"],
                    capacity=nodes_config[i].get("storage_capacity", float("inf")))
        for i in range(len(nodes_config))
    ]
    master.compute_nodes = compute_nodes
    master.nb_nodes = len(compute_nodes)
    master.avg_bandwidth = np.mean([n.bandwidth for n in compute_nodes])
    master.avg_compute_capacity = np.mean([n.compute_capacity for n in compute_nodes])

    env.process(master.sendJobOnOneNode(heterogeneous=True))
    env.process(master.sendNoStartedJobsOrTasks(heterogeneous=True))
    env.process(master.reschedulTasks(heterogeneous=True))
    for node in compute_nodes:
        env.process(node.process_tasks_homogeneous_computes())
    env.process(jobs_injector(env, master, jobs=[], job_file_path=jobs_file, config=config))

    env.run(until=until)

    if master.finished_jobs < nb_jobs:
        print(f"WARNING: only {master.finished_jobs}/{nb_jobs} jobs finished "
              f"(increase --until if needed)")

    flow_times = [j["finishing_time"] - j["arriving_time"] for j in tracker.stats_on_jobs]
    return {
        "instance": os.path.basename(instance_dir.rstrip("/")),
        "sigma": sigma,
        "nb_jobs_finished": len(flow_times),
        "avg_flow_time_s": float(np.mean(flow_times)) if flow_times else float("nan"),
        "amount_of_data_MB": tracker.total_nb_transferred_bytes,
        "nb_transfers": tracker.total_nb_transfers,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("instance_dir", help="Instance directory (e.g. traces/inst-20J-50N)")
    parser.add_argument("--sigma", type=float, default=0.05, help="Acceleration threshold (default 0.05)")
    parser.add_argument("--until", type=float, default=200000, help="Max simulation horizon (s)")
    args = parser.parse_args()

    result = run_instance(args.instance_dir, args.sigma, args.until)
    for k, v in result.items():
        print(f"{k:>20}: {v}")


if __name__ == "__main__":
    main()
