import java.io.File;
import java.util.List;
import java.util.Locale;

/**
 * Runs the Offline COP approach from the paper "Cost-Aware Replicas Placement and Tasks
 * Scheduling In Geo-Distributed Infrastructure" (Si-Mohammed et al., Section 4.1: Choco-
 * solver + Large Neighborhood Search model) on a trace generated by
 * ../generate_traces.py - the same trace (infrastructure.csv + jobs.json) used by
 * ../run_heuristic.py, to allow a direct Offline COP vs Heuristic comparison on the same
 * instances.
 *
 * The model itself (SchedulingWithDiffN.runScheduler, LNS) is copied from Flowtime 2/
 * (separate Java project), see README.md - this runner just wires a trace onto that
 * engine, the same way run_heuristic.py does on the Python side.
 *
 * Usage:
 *   java -cp "out:lib/*" RunOfflineCOP ../traces/inst-20J-50N
 *   OFFLINE_COP_TIME_LIMIT=300s java -cp "out:lib/*" RunOfflineCOP ../traces/inst-20J-50N
 *
 * `OFFLINE_COP_TIME_LIMIT` (environment variable, default "150s"): time budget for the
 * solver - the problem is NP-hard, this limit is what makes larger instances practical.
 * The last solution found before expiry is used; `proven_optimal` in the output
 * indicates whether it was also proven optimal or just the best one found within the
 * time budget (see SchedulingResult.provenOptimal).
 */
public class RunOfflineCOP {

    public static void main(String[] args) throws Exception {
        // The solver (Choco) also formats its own logs with the JVM's default Locale -
        // forcing it here avoids a "," decimal separator on a machine set to French
        // Locale (unreadable output, not comparable to run_heuristic.py's).
        Locale.setDefault(Locale.US);

        if (args.length < 1) {
            System.err.println("Usage: java -cp \"out:lib/*\" RunOfflineCOP <instance_dir> [output_dir]");
            System.exit(1);
        }
        String instanceDir = args[0];
        String outputDir = args.length >= 2 ? args[1] : null;
        if (outputDir != null) new File(outputDir).mkdirs();

        String jobsFilePath = instanceDir + File.separator + "jobs.json";
        String infraFilePath = instanceDir + File.separator + "infrastructure.csv";

        List<TraceIO.Job> jobs = TraceIO.loadJobsJSON(jobsFilePath);

        int nbData = jobs.size();
        int[] data_sizes = new int[nbData];
        int[][] works = new int[nbData][];
        int[] jobs_type = new int[nbData];
        int[] starting_times = new int[nbData];
        for (int i = 0; i < nbData; i++) {
            TraceIO.Job job = jobs.get(i);
            data_sizes[i] = job.datasetSize;
            jobs_type[i] = 0;
            int[] tasks = new int[job.nbTasks];
            java.util.Arrays.fill(tasks, job.taskDuration);
            works[i] = tasks;
            starting_times[i] = job.arrivingTime;
        }

        List<TraceIO.NodeConfig> nodes = TraceIO.loadNodeConfigCSV(infraFilePath);
        int[] bandwidths = new int[nodes.size()];
        double[] cpus = new double[nodes.size()];
        int[] storage_capacity = new int[nodes.size()];
        for (int i = 0; i < nodes.size(); i++) {
            TraceIO.NodeConfig node = nodes.get(i);
            bandwidths[i] = node.bandwidth;
            cpus[i] = node.computationNodes;
            storage_capacity[i] = node.storageCapacity;
        }

        long t0 = System.currentTimeMillis();
        SchedulingWithDiffN.SchedulingResult result = SchedulingWithDiffN.runScheduler(
                nodes.size(), nbData, data_sizes, works, jobs_type, bandwidths, cpus,
                storage_capacity, starting_times, null, 0, true, outputDir);
        double wallTimeSec = (System.currentTimeMillis() - t0) / 1000.0;

        String instanceName = new File(instanceDir.replaceAll("/+$", "")).getName();
        System.out.println();
        System.out.printf(Locale.US, "%20s: %s%n", "instance", instanceName);
        System.out.printf(Locale.US, "%20s: %d%n", "nb_jobs", nbData);
        System.out.printf(Locale.US, "%20s: %b%n", "found_solution", result.foundSolution);
        System.out.printf(Locale.US, "%20s: %b%n", "proven_optimal", result.provenOptimal);
        System.out.printf(Locale.US, "%20s: %d%n", "sum_flow_time", result.sumFlowTime);
        System.out.printf(Locale.US, "%20s: %.4f%n", "avg_flow_time_s", result.foundSolution ? (double) result.sumFlowTime / nbData : Double.NaN);
        System.out.printf(Locale.US, "%20s: %d%n", "max_flow_time_s", result.maxFlowTime);
        System.out.printf(Locale.US, "%20s: %d%n", "nb_transfers", result.nbTransfers);
        System.out.printf(Locale.US, "%20s: %.2f%n", "solve_time_s", result.solveTimeSec);
        System.out.printf(Locale.US, "%20s: %.2f%n", "wall_time_s", wallTimeSec);
        System.out.printf(Locale.US, "%20s: %d%n", "nb_solutions_found", result.nbSolutionsFound);
    }
}
