import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

/**
 * Reads the traces generated by ../generate_traces.py (same files used by
 * run_heuristic.py on the Python side: infrastructure.csv + jobs.json). Minimal extract
 * of Main.java (Flowtime 2/src/): only Job, NodeConfig, readFile/readLines/loadNodeConfigCSV
 * are kept - the rest of Main.java (infra generation, machine-specific main(), V1 CSV
 * writing...) isn't needed here.
 */
public class TraceIO {

    public static class Job {
        public int datasetSize;
        public int nbTasks;
        public int taskDuration;
        public int arrivingTime;
    }

    public static class NodeConfig {
        public int bandwidth;
        public double computationNodes;
        public double energyConsumption;
        public int storageCapacity;

        public NodeConfig(int bw, double cpu, double energy, int storageCapacity) {
            this.bandwidth = bw;
            this.computationNodes = cpu;
            this.energyConsumption = energy;
            this.storageCapacity = storageCapacity;
        }
    }

    public static String readFile(String path) throws Exception {
        return new String(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
    }

    public static List<String> readLines(String path) throws Exception {
        List<String> lines = new ArrayList<>();
        java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(path));
        String line;
        while ((line = br.readLine()) != null) {
            lines.add(line);
        }
        br.close();
        return lines;
    }

    /** Expected columns: bandwidth,computation_nodes,energy_consumption,storage_capacity
     * (same names/order as infrastructure.csv generated by generate_traces.py). */
    public static List<NodeConfig> loadNodeConfigCSV(String path) throws Exception {
        List<String> lines = readLines(path);
        List<NodeConfig> list = new ArrayList<>();

        for (int i = 1; i < lines.size(); i++) { // skip header
            String[] parts = lines.get(i).split(",");
            int bw = Integer.parseInt(parts[0]);
            double cpu = Double.parseDouble(parts[1]);
            double energy = Double.parseDouble(parts[2]);
            // storage_capacity generated by generate_traces.py (1_000_000_000, see
            // UNLIMITED_STORAGE_CAPACITY_MB) exceeds Integer.MAX_VALUE / 2, used as
            // "unlimited" on the SchedulingWithDiffN side - clamp it to stay within a
            // valid int while never making the storage constraint binding.
            long storageRaw = parts.length >= 4 ? Long.parseLong(parts[3]) : Integer.MAX_VALUE / 2;
            int storage = (int) Math.min(storageRaw, Integer.MAX_VALUE / 2);

            list.add(new NodeConfig(bw, cpu, energy, storage));
        }

        return list;
    }

    /** Reads jobs.json (same format as the one produced by generate_traces.py/read by
     * the Python jobs_injector): a list of {nb_tasks, task_duration, dataset_size,
     * arriving_time, ...}. */
    public static List<Job> loadJobsJSON(String path) throws Exception {
        String jobsText = readFile(path);
        JSONArray jobsArray = new JSONArray(jobsText);
        List<Job> jobs = new ArrayList<>();
        for (int i = 0; i < jobsArray.length(); i++) {
            JSONObject j = jobsArray.getJSONObject(i);
            Job job = new Job();
            job.datasetSize = j.getInt("dataset_size");
            job.nbTasks = j.getInt("nb_tasks");
            job.taskDuration = j.getInt("task_duration");
            job.arrivingTime = (int) j.getDouble("arriving_time");
            jobs.add(job);
        }
        return jobs;
    }
}
